/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AggregationMsg'
 * message type.
 */

public class AggregationMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 24;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new AggregationMsg of size 24. */
    public AggregationMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AggregationMsg of the given data_length. */
    public AggregationMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg with the given data_length
     * and base offset.
     */
    public AggregationMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg using the given byte array
     * as backing store.
     */
    public AggregationMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AggregationMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AggregationMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg embedded in the given message
     * at the given base offset.
     */
    public AggregationMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AggregationMsg embedded in the given message
     * at the given base offset and length.
     */
    public AggregationMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AggregationMsg> \n";
      try {
        s += "  [nodeid=0x"+Long.toHexString(get_nodeid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [size=0x"+Long.toHexString(get_size())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nodes=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_nodes(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeid
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeid' is signed (false).
     */
    public static boolean isSigned_nodeid() {
        return false;
    }

    /**
     * Return whether the field 'nodeid' is an array (false).
     */
    public static boolean isArray_nodeid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeid'
     */
    public static int offset_nodeid() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeid'
     */
    public static int offsetBits_nodeid() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'nodeid'
     */
    public int get_nodeid() {
        return (int)getUIntBEElement(offsetBits_nodeid(), 16);
    }

    /**
     * Set the value of the field 'nodeid'
     */
    public void set_nodeid(int value) {
        setUIntBEElement(offsetBits_nodeid(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeid'
     */
    public static int size_nodeid() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeid'
     */
    public static int sizeBits_nodeid() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: size
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'size' is signed (false).
     */
    public static boolean isSigned_size() {
        return false;
    }

    /**
     * Return whether the field 'size' is an array (false).
     */
    public static boolean isArray_size() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'size'
     */
    public static int offset_size() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'size'
     */
    public static int offsetBits_size() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'size'
     */
    public int get_size() {
        return (int)getUIntBEElement(offsetBits_size(), 16);
    }

    /**
     * Set the value of the field 'size'
     */
    public void set_size(int value) {
        setUIntBEElement(offsetBits_size(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'size'
     */
    public static int size_size() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'size'
     */
    public static int sizeBits_size() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodes
    //   Field type: int[], unsigned
    //   Offset (bits): 32
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodes' is signed (false).
     */
    public static boolean isSigned_nodes() {
        return false;
    }

    /**
     * Return whether the field 'nodes' is an array (true).
     */
    public static boolean isArray_nodes() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'nodes'
     */
    public static int offset_nodes(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodes'
     */
    public static int offsetBits_nodes(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'nodes' as a int[]
     */
    public int[] get_nodes() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_nodes(0); index0++) {
            tmp[index0] = getElement_nodes(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'nodes' from the given int[]
     */
    public void set_nodes(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_nodes(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'nodes'
     */
    public int getElement_nodes(int index1) {
        return (int)getUIntBEElement(offsetBits_nodes(index1), 16);
    }

    /**
     * Set an element of the array 'nodes'
     */
    public void setElement_nodes(int index1, int value) {
        setUIntBEElement(offsetBits_nodes(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'nodes'
     */
    public static int totalSize_nodes() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'nodes'
     */
    public static int totalSizeBits_nodes() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'nodes'
     */
    public static int elementSize_nodes() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'nodes'
     */
    public static int elementSizeBits_nodes() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'nodes'
     */
    public static int numDimensions_nodes() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'nodes'
     */
    public static int numElements_nodes() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'nodes'
     * for the given dimension.
     */
    public static int numElements_nodes(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
